const $=id=>document.getElementById(id);let current=null;
function showDesk(on){$('login').hidden=on;$('welcome').hidden=on;$('desk').hidden=!on;$('logout').hidden=!on;document.querySelector('main').classList.toggle('signed-in',on);if(!on){current=null;$('case').hidden=true;$('case').replaceChildren();}}
async function api(query,body){const r=await fetch('/api/cases?'+query,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const data=await r.json();if(!r.ok){if(r.status===401)showDesk(false);throw Error(data.error||'Request failed.');}return data;}
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function button(text,fn,cls){const el=node('button',text,cls);el.type='button';el.onclick=fn;return el;}
function details(values){const dl=node('dl','');for(const[k,v]of Object.entries(values))dl.append(node('dt',k),node('dd',String(v)));return dl;}
async function run(fn){const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('status').textContent='';try{await fn();}catch(e){$('status').textContent=e.message;const msg=$('dialog-error');if(msg)msg.textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}}
function render(r){current=r;const s=r.summary;const out=$('case');out.replaceChildren();out.hidden=false;
 const banner=node('div','','case-banner'),title=node('div','');title.append(node('span',r.state==='closed'?'Closed':'Under review','tag'),node('h2',s.caseNumber),node('p',r.receiverId?'Linked receiver: '+r.receiverId:'Legacy case — no receiver linked; score changes unavailable'));
 const actions=node('div','','actions');actions.append(button('Refresh',()=>run(async()=>render(await api('id='+s.caseNumber))),'secondary'),button('Export history',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));const a=node('a','');a.href=url;a.download=s.caseNumber+'-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'secondary'),button(r.state==='closed'?'Reopen case':'Close case',()=>resolve()));banner.append(title,actions);out.append(banner);
 const metrics=node('div','','metrics');for(const[label,value]of [['Reported risk',s.score+'/100'],['Active risk floor',r.reputation.riskFloor+'/100'],['Receiver trust cap',r.reputation.trustCeiling+'/100']]){const el=node('div',label,'metric');el.append(node('strong',value));metrics.append(el);}out.append(metrics,node('p',r.reputation.confirmedCases?`${r.reputation.confirmedCases} active confirmed fraud case(s). Linked demo payments are blocked at risk 95 or higher; trust is capped at 10.`:'No confirmed-case penalty. A zero risk floor is not a zero payment risk; normal payment checks still apply.','hint'));
 const tabs=node('nav','','tabs');tabs.setAttribute('aria-label','Case views');const activity=node('div','','case-columns'),evidence=node('div','','case-columns');evidence.hidden=true;const b1=button('Activity & notes',()=>select(false),'secondary'),b2=button('Evidence & identity',()=>select(true),'secondary');function select(ev){activity.hidden=ev;evidence.hidden=!ev;b1.setAttribute('aria-pressed',String(!ev));b2.setAttribute('aria-pressed',String(ev));}select(false);tabs.append(b1,b2);out.append(tabs,activity,evidence);
 const history=node('section','','case-panel');history.append(node('h3','Case timeline · '+r.timeline.length+' events'));const timeline=node('ol','','timeline');for(const event of r.timeline){const el=node('li','');el.append(node('strong',event.label||({reported:'Report received',note:'Investigation note',reopen:'Case reopened'}[event.kind]||'Case decision')),node('small',new Date(event.at).toLocaleString()+' · '+event.actor),node('p',event.text));if(event.scoreEffect)el.append(node('small',event.scoreEffect));timeline.append(el);}history.append(timeline);
 const side=node('div',''),finding=node('section','','case-panel');finding.append(node('h3','Current finding'),node('p',r.decision?.label||'Review in progress'),node('p',r.decision?.reason||'Record your evidence before closing this case. A report alone does not change receiver scores.'));const form=node('form','','case-panel');const label=node('label','Investigation note');label.htmlFor='note';const note=node('textarea','');note.id='note';note.rows=6;note.maxLength=2000;note.required=true;note.placeholder='Evidence reviewed, follow-up or observation…';const save=node('button','Save note');form.append(node('h3','Add to the case history'),label,note,node('p','Notes remain in the history. Do not enter real personal data in this demo.','hint'),save);form.onsubmit=e=>{e.preventDefault();run(async()=>{render(await api('action=note',{caseNumber:s.caseNumber,version:r.version,text:note.value}));$('status').textContent='Note saved to case history.';});};side.append(finding,form);activity.append(history,side);
 const assessment=node('section','','case-panel');assessment.append(node('h3','Sender assessment'),details({'Reported at':s.createdAt,'Category':s.category,'Amount (demo)':'INR '+s.amount,'Score basis':s.scoreNote,'VPN evidence':s.vpn,'Risk factors':s.factors.join('; ')}));const i=r.investigation,dossier=node('section','','case-panel');dossier.append(node('h3','Fictional training dossier'),node('p',i.provenance),details({'IP address':i.ipAddress,'MAC address':i.macAddress,'VPN detection':i.vpnDetection,'Location':i.location,'Phone':i.phoneNumber,'KYC status':i.kycStatus,'KYC name':i.kycName,'KYC document':i.kycDocument,'KYC address':i.kycAddress,'Evidence limitations':i.limitations}));evidence.append(assessment,dossier);
}
function resolve(){const reopen=current.state==='closed',dialog=node('dialog',''),form=node('form','');const choice=node('select','');choice.id='outcome';choice.required=!reopen;for(const[value,text]of [['','Select an outcome'],['receiver-fraud','Sender report substantiated — receiver fraud'],['receiver-cleared','Receiver cleared in this case'],['inconclusive','Inconclusive — insufficient evidence']]){const opt=node('option',text);opt.value=value;choice.append(opt);}const choiceLabel=node('label','Finding');choiceLabel.htmlFor='outcome';choice.hidden=reopen;choiceLabel.hidden=reopen;const impact=node('p','','notice');function explain(){impact.textContent=reopen?'Reopening preserves all history and removes only this case’s active penalty. Other confirmed cases remain effective.':choice.value==='receiver-fraud'?(current.receiverId?'This finding caps receiver trust at 10 and raises payment risk to at least 95, blocking linked demo payments.':'No receiver linked. The decision will be recorded without a score change.'):'No new receiver penalty. Clearing this case does not cancel findings in other cases.';}choice.onchange=explain;explain();const label=node('label','Reason and evidence reviewed');label.htmlFor='rationale';const text=node('textarea','');text.id='rationale';text.rows=5;text.minLength=15;text.maxLength=2000;text.required=true;const error=node('p','');error.id='dialog-error';error.setAttribute('role','alert');const actions=node('div','','actions');actions.append(button('Cancel',()=>dialog.close(),'secondary'),node('button','Save decision'));form.append(node('h2',reopen?'Reopen case':'Close case with a finding'),choiceLabel,choice,impact,label,text,error,actions);dialog.append(form);document.body.append(dialog);dialog.onclose=()=>dialog.remove();form.onsubmit=e=>{e.preventDefault();run(async()=>{render(await api('action='+(reopen?'reopen':'close'),{caseNumber:current.summary.caseNumber,version:current.version,text:text.value,outcome:choice.value}));dialog.close();$('status').textContent='Decision saved. Case history and receiver policy updated.';});};dialog.showModal();}
$('login').onsubmit=e=>{e.preventDefault();run(async()=>{await api('action=login',{username:$('username').value.trim(),password:$('password').value});$('password').value='';showDesk(true);$('case-number').focus();});};
$('lookup').onsubmit=e=>{e.preventDefault();run(async()=>render(await api('id='+encodeURIComponent($('case-number').value.trim().toUpperCase()))));};
$('logout').onclick=()=>run(async()=>{await api('action=logout',{});showDesk(false);});
api('action=session').then(()=>showDesk(true)).catch(()=>showDesk(false));
