import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync } from 'node:fs';
import { makeCase,reportPdf,issueSession,validSession } from '../netlify/shared/cases.mjs';
import cases from '../netlify/functions/cases.mjs';
process.env.PAYSHIELD_CASE_SESSION_SECRET='test-secret-for-unit-tests-only-123456789';
process.env.PAYSHIELD_INVESTIGATOR_USER='test-investigator';
process.env.PAYSHIELD_INVESTIGATOR_PASSWORD='test-password';
const r=makeCase({score:80,amount:2000,mode:'qr',category:'suspicious-request',basis:'qr',vpn:'detected',reasonCodes:['DEV_RISK','UNKNOWN']});
assert.match(r.summary.caseNumber,/^PS-[A-F0-9]{16}$/);assert.match(r.summary.scoreNote,/Fixed prototype/);
assert.ok(!JSON.stringify(r.summary).includes('192.0.2.42'));assert.ok(!('investigation' in r.summary));
assert.match(r.summary.vpn,/demo device data/);
assert.throws(()=>makeCase({score:999}));
const token=issueSession();assert.ok(validSession(token));assert.equal(validSession(token+'x'),false);
const request=(query,body,cookie)=>new Request('https://payshield-ai-police.netlify.app/api/cases?'+query,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(cookie?{cookie}: {})},body:body?JSON.stringify(body):undefined});
assert.equal((await cases(request('id='+r.summary.caseNumber))).status,401);
assert.equal((await cases(request('action=login',{username:'test-investigator',password:'wrong'}))).status,401);
const login=await cases(request('action=login',{username:'test-investigator',password:'test-password'}));assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);
assert.equal((await cases(request('id=invalid',null,'ps_investigator='+token))).status,400);
const pdf=await reportPdf(r.summary);mkdirSync('build-assets',{recursive:true});writeFileSync('build-assets/sender-report-sample.pdf',pdf);
console.log('PASS: redacted sender summary, authenticated lookup, invalid login, signed sessions, input validation and PDF generation.');
